# General Configuration
version: '{build}'
skip_branch_with_pr: true

# Environment Configuration
image: Visual Studio 2017
cache:
  - '%LocalAppData%\NuGet\v3-cache'

init:
  - ps: |
      If($Env:APPVEYOR_REPO_TAG -eq "true")
      {
        Write-Host "We now have a tagged release. Proper."
        Write-Host "Tag is $Env:APPVEYOR_REPO_TAG_NAME"
        $env:APPVEYOR_BUILD_VERSION=$env:APPVEYOR_REPO_TAG_NAME
        Update-AppveyorBuild -Version "$Env:APPVEYOR_REPO_TAG_NAME"
      } 
      else 
      {
        $releases = "https://api.github.com/repos/$env:APPVEYOR_REPO_NAME/releases"
        $tag = (Invoke-WebRequest $releases | ConvertFrom-Json)[0].tag_name
        $spl = $tag.Split("-")[0]
        Update-AppveyorBuild -Version "$spl.$Env:APPVEYOR_BUILD_VERSION-wip"
      }
      Write-Host "Hello. Build version is: $Env:APPVEYOR_BUILD_VERSION"

install:
  #init and update submodules
  - git submodule update --recursive --init

 # version
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: '{version}'
  assembly_file_version: '{version}'


# Build Configuration
platform: Any CPU
configuration: Release


before_build:
  - nuget restore

build:
  publish_nuget: true
  include_nuget_references: true
  publish_nuget_symbols: true
  project: SpeckleElements.sln
  verbosity: minimal

# zip everything into a zip file containing package folder structure
after_build:
  - 7z a SpeckleElements-%APPVEYOR_BUILD_VERSION%.zip "%APPVEYOR_BUILD_FOLDER%\SpeckleElements\bin\Release\*"

artifacts:
  path: SpeckleElements-%APPVEYOR_BUILD_VERSION%.zip
  name: Release

#deploy to github
deploy:
  - provider: GitHub
    release: SpeckleElements-$(APPVEYOR_BUILD_VERSION)
    tag: $(APPVEYOR_REPO_TAG_NAME)
    auth_token:
      secure: D5tPFvdQMg9sIe0sSvQjEWw4KAdOk1jyxNwiH5qP5DpDmUH6n6NgTdA+56vXS1Pe # your encrypted token from GitHub
    artifact: SpeckleElements-$(APPVEYOR_BUILD_VERSION).zip
    force_update: true
    on:              # release from master branch only
      appveyor_repo_tag: true        # deploy on tag push only